<#
.SYNOPSIS
    Regenerates the requirements-bundle.lock file with pinned versions and SHA256 hashes.

.DESCRIPTION
    Uses pip-compile (from pip-tools) to resolve all direct and transitive dependencies
    from the project's requirements.txt, pin their exact versions, and embed PyPI-verified
    SHA256 hashes. The resulting lock file is consumed by build_bundle.ps1 via
    `pip install --require-hashes` to guarantee supply-chain integrity.

    Prerequisites:
      pip install pip-tools

.EXAMPLE
    .\update_lockfile.ps1
    .\update_lockfile.ps1 -Upgrade   # resolve latest compatible versions
#>
param(
    [switch]$Upgrade
)

$ErrorActionPreference = "Stop"

$scriptDir = $PSScriptRoot
$workspaceRoot = (Resolve-Path "$scriptDir\..\..").Path
$requirementsIn = "$workspaceRoot\requirements.txt"
$lockFile = "$scriptDir\requirements-bundle.lock"

if (-not (Test-Path $requirementsIn)) {
    throw "requirements.txt not found at: $requirementsIn"
}

# Verify pip-tools is available
try {
    python -m piptools --version 2>&1 | Out-Null
} catch {
    throw "pip-tools is not installed. Run: pip install pip-tools"
}

$compileArgs = @(
    "-m", "piptools", "compile",
    "--generate-hashes",
    "--output-file=$lockFile",
    "--strip-extras",
    "--no-header"
)

if ($Upgrade) {
    $compileArgs += "--upgrade"
    Write-Host "Upgrading all dependencies to latest compatible versions..."
}

$compileArgs += $requirementsIn

Write-Host "Resolving dependencies and generating hashes..."
Write-Host "Input:  $requirementsIn"
Write-Host "Output: $lockFile"

& python @compileArgs
if ($LASTEXITCODE -ne 0) { throw "pip-compile failed. Check dependency conflicts." }

# Prepend a descriptive header
$lockContent = Get-Content $lockFile -Raw
$header = @"
#
# Supply-Chain Integrity Lock File for Diffinite Bundle
#
# Auto-generated by update_lockfile.ps1 using pip-compile --generate-hashes.
# DO NOT EDIT MANUALLY. To update, run:
#
#   .\vscode-extension\scripts\update_lockfile.ps1 -Upgrade
#
# All packages below are pinned to exact versions with SHA256 hashes verified
# against PyPI at generation time. The build_bundle.ps1 script enforces these
# hashes via `pip install --require-hashes` to prevent supply-chain attacks.
#

"@

Set-Content -Path $lockFile -Value ($header + $lockContent) -NoNewline

$lineCount = (Get-Content $lockFile).Count
$pkgCount = (Select-String -Path $lockFile -Pattern "^[a-zA-Z]" | Measure-Object).Count

Write-Host ""
Write-Host "=========================================================="
Write-Host "Lock file generated successfully."
Write-Host "  Packages pinned: $pkgCount"
Write-Host "  Total lines:     $lineCount"
Write-Host "=========================================================="
Write-Host ""
Write-Host "IMPORTANT: Review changes and commit the updated lock file."
Write-Host "  git diff vscode-extension/scripts/requirements-bundle.lock"
