name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test-vscode-bundle:
    name: Test VSCode Bundle (CD)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install Extension dependencies
      working-directory: vscode-extension
      run: npm install

    - name: Compile TypeScript
      working-directory: vscode-extension
      run: npx tsc -p ./

    - name: Test Bundle Generation & Smoke Test
      shell: pwsh
      run: |
        ./vscode-extension/scripts/build_bundle.ps1 -pythonVersion "3.12.9"

    - name: Test VSIX Packaging
      working-directory: vscode-extension
      run: |
        npm install -g @vscode/vsce@3.2.2
        vsce package --target win32-x64 --no-dependencies --allow-star-activation --out test-bundle.vsix
        Remove-Item test-bundle.vsix -ErrorAction SilentlyContinue
      shell: pwsh
